fix Agricultural Demand|Crops subcategories in AR6
pik-piam/piamInterfaces pull request #279
Opened 2024-03-20 10:27 UTC by orichters

## Purpose of this PR

old:
```
Agricultural Demand|Crops <                  Demand|Crops + Demand|Bioenergy|Bioenergy crops <
   + Agricultural Demand|Crops|Energy           + Demand|Bioenergy|Secondary products + Demand|Bioenergy|Bioenergy crops
   + Agricultural Demand|Crops|Feed             + Demand|Feed|Crops
   + Agricultural Demand|Crops|Food             + Demand|Food|Crops
   + Agricultural Demand|Crops|Other            + Demand|Agricultural Supply Chain Loss|Crops + Demand|Domestic Balanceflow|Crops
                                                  + Demand|Material|Crops + Demand|Processing|Crops + Demand|Seed|Crops
Relative difference between -17.5% and -1%, absolute difference up to 162 million t DM/yr.
```
new:
```
. Agricultural Demand|Crops =          . Demand|++|Crops + Demand|Bioenergy|+|Crops =
  + Agricultural Demand|Crops|Energy     + Demand|Bioenergy|+|Crops
  + Agricultural Demand|Crops|Feed       + Demand|Feed|+|Crops
  + Agricultural Demand|Crops|Food       + Demand|Food|+|Crops
  + Agricultural Demand|Crops|Other      + Demand|Agricultural Supply Chain Loss|+|Crops + Demand|Domestic Balanceflow|+|Crops
                                           + Demand|Material|+|Crops + Demand|Processing|+|Crops + Demand|Seed|+|Crops
Units: million t DM/yr                 Units: Mt DM/yr
```

## Checklist:
- [ ] I did not use Excel to open csv files or checked that no side-effects occur (changed values, many new quotation marks, …)

It is recommended to have a look at the [tutorial](https://github.com/pik-piam/piamInterfaces/blob/master/tutorial.md) before submission.

2024-03-20 10:42 UTC, mishkos approved these changes

2024-03-21 09:45 UTC, flohump requested changes
To solve the summation issue, `Demand|Bioenergy|+|Secondary products` needs to be subtraced from `Demand|Crops|Other`.
This can be done by setting the `piam_factor` to `-1`

2024-03-21 09:45 UTC, flohump commented on inst/templates/mapping_template_AR6.csv
> +1375;Agricultural Demand;million t DM/yr;Demand|Bioenergy|+|Secondary products;Mt DM/yr;;;;;total demand for food,non-food and feed products (crops and livestock) and bioenergy crops (1st & 2nd gener
This is a double accouting because `Demand|Bioenergy|+|Secondary products` are already included in `Demand|++|Crops`.

2024-03-21 09:45 UTC, flohump commented on inst/templates/mapping_template_AR6.csv
> +1375;Agricultural Demand;million t DM/yr;Demand|Bioenergy|+|Secondary products;Mt DM/yr;;;;;total demand for food,non-food and feed products (crops and livestock) and bioenergy crops (1st & 2nd gener
Therefore, `Demand|Bioenergy|+|Secondary products` should not be added here.

2024-03-21 09:45 UTC, flohump commented on inst/templates/mapping_template_AR6.csv
> +1376;Agricultural Demand|Crops;million t DM/yr;Demand|Bioenergy|+|Secondary products;Mt DM/yr;;;;;total demand for food,non-food and feed crops and bioenergy crops (1st & 2nd generation);M
same as above.

2024-03-21 13:42 UTC, flohump approved these changes
Looks good now. 
Many thanks for spotting the gaps.

2024-03-21 13:45 UTC, merged

2024-03-21 13:46 UTC, orichters commented
The gaps basically spot themselves, once you define the summation rules. I can only encourage to add more of them.